version: '3.7'
services:
  web:
    build: .
    command: uwsgi --http :8000 --chdir MyMoments/ --module MyMoments.wsgi
    volumes:
      - "${PWD}/:/project/"
    ports:
      - "8000:8000"
    env_file:
      - MyMoments/.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - "postgres_data:/var/lib/postgresql/data/"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
#  uwsgi:
#    build: .
#      context: .
#      dockerfile: uwsgi.dockerfile



volumes:
    postgres_data: