version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: dockerfiles/django.dockerfile
    command: bash -c "
      python MyMoments/manage.py wait_for_database
      &&
      python MyMoments/manage.py makemigrations --noinput
      &&
      python MyMoments/manage.py migrate  --noinput
      && 
      (python MyMoments/manage.py collectstatic --noinput)
      &&
      uwsgi --ini /etc//uwsgi.ini"
    volumes:
      - "${PWD}/:/project/"
      - sock:/sock
    env_file:
      - MyMoments/.env
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: dockerfiles/postgres.dockerfile
    volumes:
      - "postgres_data:/var/lib/postgresql/data/"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django_password
      - POSTGRES_DB=hello_django_dev
  webserver:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    volumes:
      - "${PWD}/MyMoments/static/:/etc/nginx/static:ro"
      - sock:/sock
    ports:
      - "8080:8080"
    depends_on:
      - web


volumes:
    postgres_data:
    sock: