version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: dockerfiles/django.dockerfile
    command: bash -c "
      python MyMoments/manage.py wait_for_database
      &&
      python MyMoments/manage.py makemigrations --noinput
      &&
      python MyMoments/manage.py migrate  --noinput
      && 
      (python MyMoments/manage.py collectstatic --noinput)
      &&
      uwsgi --ini /etc//uwsgi.ini"
    volumes:
      - "${PWD}/:/project/"
      - sock:/sock
    env_file:
      - MyMoments/.env
    depends_on:
      - db
    networks:
      - django-network

  db:
    build:
      context: .
      dockerfile: dockerfiles/postgres.dockerfile
    volumes:
      - "postgres_data:/var/lib/postgresql/data/"
    networks:
      - django-network
#    environment:
#      - POSTGRES_HOST_AUTH_METHOD=trust
  webserver:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    volumes:
      - "${PWD}/MyMoments/static/:/etc/nginx/static:ro"
      - "${PWD}/MyMoments/media/:/etc/nginx/media:ro"
      - sock:/sock
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - django-network


volumes:
    postgres_data:
    sock:

networks:
      django-network:
          driver: bridge