# Generated by Django 4.1.3 on 2022-11-17 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follower',
            options={'verbose_name': 'like', 'verbose_name_plural': 'likes'},
        ),
    ]
