# Generated by Django 4.1.3 on 2022-11-17 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0002_alter_follower_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follower',
            options={'verbose_name': 'follower', 'verbose_name_plural': 'followers'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'like', 'verbose_name_plural': 'likes'},
        ),
    ]
