# Generated by Django 4.1.5 on 2023-01-24 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('moments', '0004_remove_profile_followers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('object_id', 'liked_user', 'content_type')},
        ),
    ]
